services:
  postgres:
    image: postgres:16
    container_name: travel_wise_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: travel_wise_demo
    volumes:
      - ./src/main/resources/db/travel_wise_dump.sql:/docker-entrypoint-initdb.d/travel_wise_dump.sql
    ports:
      - "5432:5432"

#  backend:
#    build: .
#    container_name: travel_wise_backend
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/travel_wise_demo
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: 1234
#
#    ports:
#      - "8080:8080"
#    restart: always